import MetaShoe from "#models/meta/shoe";
import { BaseSeeder } from "@adonisjs/lucid/seeders";

export default class MetaShoeSeeder extends BaseSeeder {
  public async run () {
    await MetaShoe.createMany([
      {
        product_id: 1,
        brand_id: 1,
        description: 'Chaussure Nike Homme Basket',
        images: 'https://m.media-amazon.com/images/I/81j7lKOrUgL._AC_SX575_.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'male',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 2,
        brand_id: 1,
        description: 'Nike Homme Revolution 6 Nn Chaussures de Course',
        images: 'https://m.media-amazon.com/images/I/51DeSu3qTpL._AC_SY695_.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'male',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 3,
        brand_id: 1,
        description: 'Nike Air Max 95 Corteiz Pink Beam',
        images: 'https://m.media-amazon.com/images/I/41J4N5nPURL._AC_UF480,480_SR480,480_.jpg',
        size: '42, 43, 44, 45',
        color: 'Pink',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'male',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 4,
        brand_id: 1,
        description: 'Nike Air Max 1 \'86 OG Big Bubble Sport Red',
        images: 'https://m.media-amazon.com/images/I/41J4N5nPURL._AC_UF480,480_SR480,480_.jpg',
        size: '42, 43, 44, 45',
        color: 'Red',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'male',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 5,
        brand_id: 1,
        description: 'Nike Air Max 1 Design by Japan (W)',
        images: 'https://m.media-amazon.com/images/I/41J4N5nPURL._AC_UF480,480_SR480,480_.jpg',
        size: '42, 43, 44, 45',
        color: 'Green',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'male',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 6,
        brand_id: 2,
        description: 'Adidas Yeezy Boost 350 Turtledove (2022)',
        images: 'https://m.media-amazon.com/images/I/71GUUtRndkL._AC_SY695_.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Primeknit',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 7,
        brand_id: 2,
        description: 'Adidas Yeezy Boost 350 V2 Bone',
        images: 'https://m.media-amazon.com/images/I/71GUUtRndkL._AC_SY695_.jpg',
        size: '42, 43, 44, 45',
        color: 'White',
        sole_material: 'Rubber',
        upper_material: 'Primeknit',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 8,
        brand_id: 2,
        description: 'Adidas Yeezy Boost 350 V2 Oreo',
        images: 'https://m.media-amazon.com/images/I/71GUUtRndkL._AC_SY695_.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Primeknit',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 9,
        brand_id: 2,
        description: 'Adidas Yeezy Boost 350 V2 Dazzling Blue',
        images: 'https://m.media-amazon.com/images/I/71GUUtRndkL._AC_SY695_.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue',
        sole_material: 'Rubber',
        upper_material: 'Primeknit',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 10,
        brand_id: 2,
        description: 'Adidas Yeezy Boost 350 V2 Beluga Reflective',
        images: 'https://m.media-amazon.com/images/I/71GUUtRndkL._AC_SY695_.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Primeknit',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 11,
        brand_id: 3,
        description: 'Puma XT S',
        images: 'https://example.com/puma_xt_s.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue/White',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 12,
        brand_id: 3,
        description: 'Puma XS850 Peter',
        images: 'https://example.com/puma_xs850_peter.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 13,
        brand_id: 3,
        description: 'Puma X-Ray Tour',
        images: 'https://example.com/puma_xray_tour.jpg',
        size: '42, 43, 44, 45',
        color: 'Multicolor',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 14,
        brand_id: 3,
        description: 'Puma X-Ray Speed',
        images: 'https://example.com/puma_xray_speed.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 15,
        brand_id: 3,
        description: 'Puma X-Ray Speed (White/Blue/Red)',
        images: 'https://example.com/puma_xray_speed_white_blue_red.jpg',
        size: '42, 43, 44, 45',
        color: 'White/Blue/Red',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 16,
        brand_id: 4,
        description: 'Reebok Court Clean',
        images: 'https://example.com/reebok_court_clean.jpg',
        size: '42, 43, 44, 45',
        color: 'White',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'female',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 17,
        brand_id: 4,
        description: 'Reebok Club C Double Revenge',
        images: 'https://example.com/reebok_club_c_double_revenge.jpg',
        size: '42, 43, 44, 45',
        color: 'White/Green',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'female',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 18,
        brand_id: 4,
        description: 'Reebok Court Advance',
        images: 'https://example.com/reebok_court_advance.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 19,
        brand_id: 4,
        description: 'Reebok Court Retro',
        images: 'https://example.com/reebok_court_retro.jpg',
        size: '42, 43, 44, 45',
        color: 'White',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'female',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 20,
        brand_id: 5,
        description: 'New Balance 574 Core',
        images: 'https://example.com/new_balance_574_core.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'male',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 21,
        brand_id: 5,
        description: 'New Balance 2002R',
        images: 'https://example.com/new_balance_2002r.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'male',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 22,
        brand_id: 5,
        description: 'New Balance Made in USA 993',
        images: 'https://example.com/new_balance_made_in_usa_993.jpg',
        size: '42, 43, 44, 45',
        color: 'Green',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 23,
        brand_id: 5,
        description: 'New Balance 9060 Blue',
        images: 'https://example.com/new_balance_9060_blue.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 24,
        brand_id: 5,
        description: 'New Balance 1906R',
        images: 'https://example.com/new_balance_1906r.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 25,
        brand_id: 5,
        description: 'New Balance 9060 Green',
        images: 'https://example.com/new_balance_9060_green.jpg',
        size: '42, 43, 44, 45',
        color: 'Green',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      // Asics
      {
        product_id: 26,
        brand_id: 6,
        description: 'Asics Gel-Kayano 27',
        images: 'https://example.com/asics_gel_kayano_27.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 27,
        brand_id: 6,
        description: 'Asics Gel-Nimbus 23',
        images: 'https://example.com/asics_gel_nimbus_23.jpg',
        size: '42, 43, 44, 45',
        color: 'White',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 28,
        brand_id: 6,
        description: 'Asics GT-2000 9',
        images: 'https://example.com/asics_gt_2000_9.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 29,
        brand_id: 6,
        description: 'Asics Gel-Excite 8',
        images: 'https://example.com/asics_gel_excite_8.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 30,
        brand_id: 6,
        description: 'Asics Gel-Venture 7',
        images: 'https://example.com/asics_gel_venture_7.jpg',
        size: '42, 43, 44, 45',
        color: 'Green',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },

      // Converse
      {
        product_id: 31,
        brand_id: 7,
        description: 'Converse Chuck Taylor All Star',
        images: 'https://example.com/converse_chuck_taylor_all_star.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Canvas',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 32,
        brand_id: 7,
        description: 'Converse One Star Pro',
        images: 'https://example.com/converse_one_star_pro.jpg',
        size: '42, 43, 44, 45',
        color: 'White',
        sole_material: 'Rubber',
        upper_material: 'Suede',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 33,
        brand_id: 7,
        description: 'Converse Pro Leather',
        images: 'https://example.com/converse_pro_leather.jpg',
        size: '42, 43, 44, 45',
        color: 'Red',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 34,
        brand_id: 7,
        description: 'Converse Jack Purcell',
        images: 'https://example.com/converse_jack_purcell.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue',
        sole_material: 'Rubber',
        upper_material: 'Canvas',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 35,
        brand_id: 7,
        description: 'Converse Star Player',
        images: 'https://example.com/converse_star_player.jpg',
        size: '42, 43, 44, 45',
        color: 'Green',
        sole_material: 'Rubber',
        upper_material: 'Canvas',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },

      // Vans
      {
        product_id: 36,
        brand_id: 8,
        description: 'Vans Old Skool',
        images: 'https://example.com/vans_old_skool.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Canvas',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 37,
        brand_id: 8,
        description: 'Vans Sk8-Hi',
        images: 'https://example.com/vans_sk8_hi.jpg',
        size: '42, 43, 44, 45',
        color: 'White',
        sole_material: 'Rubber',
        upper_material: 'Suede',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 38,
        brand_id: 8,
        description: 'Vans Authentic',
        images: 'https://example.com/vans_authentic.jpg',
        size: '42, 43, 44, 45',
        color: 'Red',
        sole_material: 'Rubber',
        upper_material: 'Canvas',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 39,
        brand_id: 8,
        description: 'Vans Era',
        images: 'https://example.com/vans_era.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue',
        sole_material: 'Rubber',
        upper_material: 'Canvas',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 40,
        brand_id: 8,
        description: 'Vans Slip-On',
        images: 'https://example.com/vans_slip_on.jpg',
        size: '42, 43, 44, 45',
        color: 'Green',
        sole_material: 'Rubber',
        upper_material: 'Canvas',
        inside_material: 'Textile',
        closure_type: 'Slip-On',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },

      // Timberland
      {
        product_id: 41,
        brand_id: 9,
        description: 'Timberland 6-Inch Premium Waterproof Boot',
        images: 'https://example.com/timberland_6_inch_premium_waterproof_boot.jpg',
        size: '42, 43, 44, 45',
        color: 'Brown',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 42,
        brand_id: 9,
        description: 'Timberland PRO Boondock',
        images: 'https://example.com/timberland_pro_boondock.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 43,
        brand_id: 9,
        description: 'Timberland White Ledge Mid Waterproof Boot',
        images: 'https://example.com/timberland_white_ledge_mid_waterproof_boot.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 44,
        brand_id: 9,
        description: 'Timberland Earthkeepers Original',
        images: 'https://example.com/timberland_earthkeepers_original.jpg',
        size: '42, 43, 44, 45',
        color: 'Green',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 45,
        brand_id: 9,
        description: 'Timberland Mt. Maddsen Waterproof Boot',
        images: 'https://example.com/timberland_mt_maddsen_waterproof_boot.jpg',
        size: '42, 43, 44, 45',
        color: 'Brown',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },

      // Skechers
      {
        product_id: 46,
        brand_id: 10,
        description: 'Skechers D\'Lites',
        images: 'https://example.com/skechers_dlites.jpg',
        size: '42, 43, 44, 45',
        color: 'White',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 47,
        brand_id: 10,
        description: 'Skechers Go Walk 5',
        images: 'https://example.com/skechers_go_walk_5.jpg',
        size: '42, 43, 44, 45',
        color: 'Gray',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Slip-On',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 48,
        brand_id: 10,
        description: 'Skechers Flex Advantage',
        images: 'https://example.com/skechers_flex_advantage.jpg',
        size: '42, 43, 44, 45',
        color: 'Black',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 49,
        brand_id: 10,
        description: 'Skechers Ultra Flex',
        images: 'https://example.com/skechers_ultra_flex.jpg',
        size: '42, 43, 44, 45',
        color: 'Blue',
        sole_material: 'Rubber',
        upper_material: 'Mesh',
        inside_material: 'Textile',
        closure_type: 'Slip-On',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        product_id: 50,
        brand_id: 10,
        description: 'Skechers After Burn Memory Fit',
        images: 'https://example.com/skechers_after_burn_memory_fit.jpg',
        size: '42, 43, 44, 45',
        color: 'Brown',
        sole_material: 'Rubber',
        upper_material: 'Leather',
        inside_material: 'Textile',
        closure_type: 'Lace-up',
        heel_type: 'Flat',
        heel_height: '2 inches',
        product_size: 'M',
        product_gender: 'unisex',
        created_at: new Date(),
        updated_at: new Date()
      },
    ])
  }
}
